@local = http://localhost:8080
@deployed = https://maneja-tickets.onrender.com

// Set to "local" or "deployed" based on which environemnt you're testing.
@host = {{local}}

#################
# USERS
#################

### CREATE USER
POST {{host}}/auth/create HTTP/1.1
Content-Type: application/json

{
    "firstName": "Marcos",
    "lastName": "Antunes",
    "username": "marcos jr",
    "email": "marcos@antuness.com",
    "phoneNumber": "123-123-3333",
    "password": "testing123",
    "jobPosition": "web backend developer"
}

### LOGIN
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{  
    "email": "marcos@antunes.com",
    "password": "testing123"
}

### UPDATE USER
PUT {{host}}/auth/account/6569bcfd23faef37e870c298 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Marcos",
    "lastName": "Antunes",
    "username": "marcos jr",
    "email": "marcos@antunes.com",
    "phoneNumber": "123-123-3333",
    "jobPosition": "web backend developer"

}

### DELETE USER
DELETE {{host}}/auth/account/6568d4ca16eaa1dfd891beca HTTP/1.1

### LOG OUT
GET {{host}}/auth/logout

#################
# GOOGLE USERS
#################

### GOOGLE LOGIN
POST {{host}}/google

### UPDATE GOOGLE USER
PUT {{host}}/google/update/65731e77d84fcef1ffba8208 HTTP/1.1
Content-Type: application/json

{
    "username": "Bruce Wayne"
}

### DELETE GOOGLE USER
DELETE {{host}}/google/delete/65731e77d84fcef1ffba8208 HTTP/1.1

#################
# TICKETS
#################

### GET ALL TICKETS
GET {{host}}/tickets/

### GET TICKET BY ID
GET {{host}}/tickets/656a22bd72039c93a3d50222

### CREATE TICKET
POST {{host}}/tickets HTTP/1.1
Content-Type: application/json

{
  "userId": "656a1ba79b85f94a3b261761",
  "title": "Batmobile Won't Start",
  "description": "The Batmobile won't start. Gotham needs me, but it says it needs the latest software update.",
  "priorityLevel": "Medium",
  "assignedEmployee": "6569bcfd23faef37e870c298"
}

### UPDATE TICKET
PUT {{host}}/tickets/656a22bd72039c93a3d50222 HTTP/1.1
Content-Type: application/json

{
  "priorityLevel": "High"
}

### DELETE TICKET BY ID
DELETE {{host}}/tickets/65592886744f7d0ebe92c28d

#################
# RESOLUTIONS
#################

### GET ALL RESOLUTIONS
GET {{host}}/resolutions/

### GET RESOLUTION BY ID
GET {{host}}/resolutions/656a290cc420deb53c7d03e6

### CREATE RESOLUTION
POST {{host}}/resolutions HTTP/1.1
Content-Type: application/json

{
  "ticketId": "6565e2555f22d1e51377e14b",
  "description": "Updated the Batmobile software",
  "resolvedByEmployee": "6569bcfd23faef37e870c298"
}

### UPDATE RESOLUTION
PUT {{host}}/resolutions/656a290cc420deb53c7d03e6 HTTP/1.1
Content-Type: application/json

{
  "description": "Updated the Batmobile software to version 19.39"
}

### DELETE RESOLUTION BY ID
DELETE {{host}}/resolutions/656a290cc420deb53c7d03e6